version: '3'
services:
  client: 
    container_name: game-client
    image: node:19-alpine
    working_dir: /client
    volumes:
      - ./client:/client
    command: npm run dev
    environment:
      VITE_API_URL: http://localhost:7000
      VITE_WS_URL: ws://localhost:7000
    ports: 
      - 3000:3000

  server:
    container_name: game-server
    image: golang
    working_dir: /server
    volumes:
      - ./server:/server
    command: sh -c "go mod tidy && go run ."
    ports:
      - 7000:7000
    environment:
      ENV: development
      DOMAIN: localhost
      PORT: 7000
