version: '3'
services:
  client: 
    container_name: game-client
    image: node:19-alpine
    working_dir: /client
    volumes:
      - ./client:/client
    command: npm run dev
    environment:
      VITE_DOMAIN_URL: http://localhost:3000
      VITE_API_URL: http://localhost:7000
      VITE_NODE_ENV: development
    ports: 
      - 3000:3000

  server:
    container_name: game-server
    image: golang
    working_dir: /server
    volumes:
      - ./server:/server
    command: sh -c "go mod tidy && go run ."
    environment:
      ENV: development
      PORT: 443
      DB_USER: postgres
      DB_PASS: 12345
      DB_HOST: db
      DB_NAME: game

  db:
    container_name: game-db
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: game
