# fly.toml file generated for the-game-server on 2023-03-24T01:55:04+01:00

app = "the-game-server"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "arn"
processes = []

[env]
  DOMAIN = "thegame.live"
  PORT   = "8080"
  ENV    = "production"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
